# Generated by Django 4.2.5 on 2023-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0002_rename_usuarios_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.IntegerField(max_length=3),
        ),
    ]
