# Generated by Django 4.2.5 on 2023-10-30 18:32

import app_cad_usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0003_alter_usuario_idade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.PositiveSmallIntegerField(
                validators=[app_cad_usuarios.models.validate_idade]
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(
                max_length=255, validators=[app_cad_usuarios.models.validate_nome]
            ),
        ),
    ]
